### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by ChanCheryl** [humanoid-path-planner/hpp-doc#39] opened 2019-03-04 08:09 UTC
Hi,
I can't install the HPP system.
I used the method mentioned here, https://humanoid-path-planner.github.io/hpp-doc/download.html. But I couldn't download it. Why?
I also used the method mentioned here, https://github.com/humanoid-path-planner/hpp-doc/blob/master/doc/instructions.md. The result is useless.
![1722366642](https://user-images.githubusercontent.com/35367606/53719328-bab6bd00-3e98-11e9-92e2-3475484f3ad7.jpg)

Do I have to download any packages before using the command to install in the terminal ? Could you give me some advice about the installation?
Thanks

**Comment by nim65s** [comment] 2019-03-04 08:23
Hi,

You should remove the starting
    ```bash

and the trailing

    ```

**Comment by ChanCheryl** [comment] 2019-03-05 08:08
Hi，
You are right. Thank you very much.
But when I went to step7, I encountered a new problem.I couldn't download the files.

![857876063](https://user-images.githubusercontent.com/35367606/53789806-52cba980-3f60-11e9-8d51-8e5dd047860a.jpg)

Then I also tried to run them separately. But the result was the same.
![779933200](https://user-images.githubusercontent.com/35367606/53789944-ab9b4200-3f60-11e9-8dc7-3836c5d72840.jpg)

Do you have any suggestions? Sorry to bother you again.
Thanks

**Comment by florent-lamiraux** [comment] 2019-03-05 08:21
You types `cd DEVEL_HPP_DIR/src` instead of `cd $DEVEL_HPP_DIR/src`.
You need to define environment variable `DEVEL_HPP_DIR` to tell the Makefile where to download, compile and install the code.

**Comment by ChanCheryl** [comment] 2019-03-05 11:12
I have changed it as what you said, but it still has some problems.
![583489516](https://user-images.githubusercontent.com/35367606/53796691-a09bde00-3f6f-11e9-987f-13e491232618.jpg)
And this is the variable I set in my  .bashrc.
![1350319662](https://user-images.githubusercontent.com/35367606/53801617-8e736d00-3f7a-11e9-91fc-0e3a69223744.jpg)
Thanks

**Comment by florent-lamiraux** [comment] 2019-03-05 11:19
command `cd /src/collada-dom/build-rel` in the terminal shows that the variable is not set correctly.
in `.bashrc`, you should add
`export DEVEL_HPP_DIR=/home/cheryl/HPP`

Be sure to start a new terminal to make sure that .bashrc is read.

Before running `make`, type
`echo $DEVEL_HPP_DIR`
to be sure that the variable is correctly set.

**Comment by ChanCheryl** [comment] 2019-03-05 12:05
You're correct! But when it ran for a while, it had a similar problem.
![1846730791](https://user-images.githubusercontent.com/35367606/53804222-e6fa3880-3f81-11e9-859e-71e791579c18.jpg)
And I think the variable is correctly this time.
![782900073](https://user-images.githubusercontent.com/35367606/53804264-08f3bb00-3f82-11e9-9820-46d89b4a9ac2.jpg)

**Comment by jmirabel** [comment] 2019-03-05 12:18
Git complains that it couldn't find branch v4.3.0 on hpp-fcl. This should not have happened. v4.3.0 is not a branch but a tag. It is a valid input to the -b option. From git doc
>       --branch <name>, -b <name>
>           Instead of pointing the newly created HEAD to the branch pointed to by the cloned repository’s HEAD, point to <name> branch instead. In a non-bare repository, this is the branch that will be
>           checked out.  --branch can also take tags and detaches the HEAD at that commit in the resulting repository.

What is your OS ? What's your version of git ?
For me
```bash
$ git --version 
git version 2.7.4
```

**Comment by ChanCheryl** [comment] 2019-03-05 12:28
My version of git is the same as yours.

**Comment by jmirabel** [comment] 2019-03-05 12:42
I don't know how it is possible that we missed that bug. #40 should fix your issue. Meanwhile, you can pull this Makefile instead: https://github.com/jmirabel/hpp-doc/blob/master/doc/Makefile

**Comment by nim65s** [comment] 2019-03-05 12:44
The issue is that hpp-fcl does not have a v4.3.0.

**Comment by jmirabel** [comment] 2019-03-05 12:50
> The issue is that hpp-fcl does not have a v4.3.0.

You are right. It is on my computer but it wasn't pushed.

**Comment by jmirabel** [comment] 2019-03-05 12:55
> I don't know how it is possible that we missed that bug. #40 should fix your issue. Meanwhile, you can pull this Makefile instead: https://github.com/jmirabel/hpp-doc/blob/master/doc/Makefile

I updated the master branch on my fork. You can (re)download the file now.

**Comment by ChanCheryl** [comment] 2019-03-06 08:35
I changed the Makefile as you suggested.But it still doesn't work.
![1646935990](https://user-images.githubusercontent.com/35367606/53866900-993b0a00-402d-11e9-9b2d-acfef6c77da9.jpg)

**Comment by florent-lamiraux** [comment] 2019-03-06 08:55
Indeed, the master branch does not compile. Your problem has been fixed in a later commit.
To work around the issue, I suggest that you do
`cd $DEVEL_HPP_DIR/src/gepetto-viewer-corba`
`git checkout -b devel origin/devel`
`cd $DEVEL_HPP_DIR/src`
`make all`

Then, let me know whether this fixes your issue.

**Comment by ChanCheryl** [comment] 2019-03-06 09:49
Thanks. But I think it doesn't work. It still has some problems.
![1927803314](https://user-images.githubusercontent.com/35367606/53871980-3307b480-4038-11e9-8158-533cb1575dc0.jpg)

**Comment by florent-lamiraux** [comment] 2019-03-06 10:01
Can you check that directory `collada-dom` has been checked out ?
Can you type `pkg-config --modversion collada14dom` ?
can you type `echo $PKG_CONFIG_PATH` ?

**Comment by ChanCheryl** [comment] 2019-03-06 10:09
![27554008](https://user-images.githubusercontent.com/35367606/53873186-bf1adb80-403a-11e9-9bad-05bb2d495632.jpg)
Is there anything wrong？

**Comment by florent-lamiraux** [comment] 2019-03-06 10:12
I do not understand what happened.
Can you type `make collada-dom.install` in `$DEVEL_HPP_DIR/src` ?

**Comment by jmirabel** [comment] 2019-03-06 10:16
The paths in the two previous messages are different. In your `PKG_CONFIG_PATH`, you have `~/kinova/devel/lib`, while the sources of HPP are in `~/HPP/src`. Given the above pictures, binaries are installed in  `~/HPP/install`.

Did you source the config file ?
Can you provide the output of:
```bash
echo $DEVEL_HPP_DIR
cat  $DEVEL_HPP_DIR/config.sh
```

**Comment by florent-lamiraux** [comment] 2019-03-06 10:23
That's right, I missed the point.

**Comment by ChanCheryl** [comment] 2019-03-06 10:26
Here is the result of `make collada-dom.install`
![1234936804](https://user-images.githubusercontent.com/35367606/53874156-ca6f0680-403c-11e9-9878-bec45cfecdf7.jpg)
And here is the result of `echo $DEVEL_HPP_DIR     cat  $DEVEL_HPP_DIR/config.sh`
![1833975297](https://user-images.githubusercontent.com/35367606/53874295-1cb02780-403d-11e9-98eb-80a00853d58a.jpg)
I'm sure that I source the config file before.
Thanks

**Comment by jmirabel** [comment] 2019-03-06 10:36
Then, you have to understand why the environment variable PKG_CONFIG_PATH does not contain `~/HPP/install/lib/pkgconfig`. Open a new terminal, source the file and check the environment variable.

If they are OK, then, try again the installation.

**Comment by florent-lamiraux** [comment] 2019-03-06 10:38
Maybe your `.bashrc` modifies variable `PKG_CONFIG_PATH` after you source `config.sh`...

**Comment by nim65s** [comment] 2019-03-06 10:39
@ChanCheryl Do you really need the source version ? Do you know that you could install HPP from a binary source, without the need to understand all the compilation process ?

**Comment by ChanCheryl** [comment] 2019-03-06 10:51
@jmirabel @florent-lamiraux Thank you very much. I well try again.

**Comment by ChanCheryl** [comment] 2019-03-06 10:51
@nim65s Sorry, I don't know how to nstall HPP from a binary source. Because I didn't find the relevant installation tutorial. I just found this one https://github.com/jmirabel/hpp-doc/blob/master/doc/instructions.md

**Comment by nim65s** [comment] 2019-03-06 11:05
@ChanCheryl Don't be sorry, it's not your fault, we may be lacking proper documentation about that on this project. 
You can install robotpkg's binary repository with the following commands (if you are on Ubuntu 16.04, otherwise you will have to adapt the `xenial` part):
```
curl http://robotpkg.openrobots.org/packages/debian/robotpkg.key | sudo apt-key add -
sudo tee /etc/apt/sources.list.d/robotpkg.list <<EOF
deb [arch=amd64] http://robotpkg.openrobots.org/wip/packages/debian/pub xenial robotpkg
deb [arch=amd64] http://robotpkg.openrobots.org/packages/debian/pub xenial robotpkg
EOF
sudo apt update
sudo apt install robotpkg-hpp-tutorial
```

**Comment by ChanCheryl** [comment] 2019-03-06 11:35
@nim65s Thank you very much!!!
I am going to learn how to use your platform. Can you give me any advice?

**Comment by florent-lamiraux** [comment] 2019-03-06 12:36
You can have a look at the tutorial at
/opt/openrobots/share/doc/hpp_tutorial/doxygen-html/index.html

**Comment by jmirabel** [comment] 2019-03-09 11:18
The installation problem is solved. @ChanCheryl re-open if you need some more help.

**Closed by jmirabel** 2019-03-09 11:18 UTC
